meetings:
    - 
        type: daily scrum meeting
        min_start: 11:00 #минимальное время начала
        max_start: 15:00 #макс время начала
        duration: 30 #продолжительность
        weekday: Any
    - 
        type: sprint planing
        min_start: 11:00
        max_start: 15:00
        duration: 60
        weekday: Monday
    - 
        type: retrospective 
        min_start: 11:00
        max_start: 18:00
        duration: 60
        weekday: Friday
users:
    -
        name: Aidar
        tlg_id: 1111111111 #идентификатор в телеграм
        meetings: daily,sprint #в каких митингах необходимо участие
    - 
        name: Vladimir
        tlg_id: 1111111111
        meetings: sprint
    -
        name: Berdibek
        tlg_id: berda0_o
        meetings: daily,sprint,retrospective